<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout_sc-iNWwEs qLLqI</name>
   <tag></tag>
   <elementGuidId>1cc1b7c4-ce59-4c3c-a789-cabf6441d150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div[3]/div[2]/div/form/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-iNWwEs.qLLqI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-iNWwEs qLLqI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-wAnfg gwBHuV&quot;]/div[@class=&quot;sc-dpkrwT dQzQeh&quot;]/div[@class=&quot;sc-jtJlRs AIVoc&quot;]/div[@class=&quot;adminPageRightWrapper&quot;]/div[@class=&quot;sc-gCLdxd lbFgvJ&quot;]/div[1]/form[1]/div[@class=&quot;sc-iNWwEs qLLqI&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[3]/div[2]/div/form/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
   </webElementXpaths>
</WebElementEntity>
